name: AdminTools
main: dev.ikara.admintools.AdminTools
version: 1.0
commands:
  velocitytest:
    description: Test if a player has modified velocity
    usage: /<command> <player>
    aliases: [vt, kbtest, velo]
  nofalltest:
    description: Test if a player has no fall damage
    usage: /<command> <player>
    aliases: [nft]
  cpstest:
    usage: /cpstest <player> [duration]
    description: Measure a player's clicks per second.
    aliases: [cps, testcps]
  killauratest:
    usage: /killauratest <player>
    description: Test to see if a player has Kill Aura.
    aliases: [ka, katest, testka]