name: AdminTools
main: dev.ikara.admintools.AdminTools
version: 1.0
commands:
  velocitytest:
    description: Test if a player has modified velocity
    usage: /<command> <player>
    aliases: [vt, kbtest, testkb, velo]
  nofalltest:
    description: Test if a player has no fall damage
    usage: /<command> <player>
    aliases: [nft, testnofall]
  cpstest:
    usage: /cpstest <player> [duration]
    description: Measure a player's clicks per second.
    aliases: [cpst, testcps, checksps, cpscheck]
  killauratest:
    usage: /killauratest <player>
    description: Test to see if a player has Kill Aura.
    aliases: [kat, katest, testka]
  aimanalysis:
    usage: /aimanalysis <player>
    description: Test to see if a player has Aim Assist.
    aliases: [aa, aat]
  fakeore:
    usage: /fakeore <player> [material] [amount] [radius] [durationSeconds]
    description: Test to see if a player is using X-Ray
  fakebase:
    usage: /fakebase <player> [schematic] [distance] [durationSeconds]
    description: Test to see if a player is using X-Ray
    aliases: [fbt]